### ISSUE TITLE
Open folder without specifiying "open" keyword

### ISSUE THREAD

**Issue by brpaz** [tinytacoteam/zazu-file-finder#10]
Hello.

If i type for example "Pictures",  zazu will find my Pictures folder just fine but when I click on it it dont do anything. If I start my search with "open" keyword it works fine.

I think It should work on both ways.

Also it seems finder can only find directories at first level. For example, If I search for Pictures it will find my $HOME/Pictures directory but if I search for "Events" which is a subfolder of my "Pictures" folder it wont find anything.

**Comment by blainesch** [comment]
what operating system are you on?

If you just type in "pictures" it should only file applications. On a mac those are mostly ".app" files, on a linux those are "executable" files. My guess is that your "Pictures" is marked as executable which is why it's incorrectly showing up in the app search.

The "open pictures" command is on the fly and traverses a lot more, where as "pictures" uses a local cache. They both traverse multiple directories.

So to add the "open *" command without "open" would be really slow.

I hope that helps clarify! :D
