### ISSUE TITLE
Mac alternative adapter for spotlight enabled results (including file metadata)

### ISSUE THREAD

**Issue by afaur** [tinytacoteam/zazu-file-finder#18]
Looks like `mdfind` will query the spotlight database on mac osx.  
The command does not support regex, but results could be additionally filtered after being obtained.

`mdfind` can also be set to:
  - Look only in specific indexed directories
  - Return attributes/metadata from certain filetypes.

Looks like there is a node wrapper here:
  - https://github.com/brandonhorst/node-mdfind

**Comment by blainesch** [comment]
There is some os-specific logic, but this would cause this plugin to have two 100% different code paths. What does the community think about adding this to `zazu-file-finder` vs creating something like `zazu-mac-mdfind` ?

**Comment by brpaz** [comment]
For Linux, maybe we can use [Tracker](https://wiki.gnome.org/Projects/Tracker). dont know if a similar engine exists for windows.
I think it would be nice to create some generic npm package, capable of searching spotlight or tracker (a separate package for each). It could be usefull for plugin developers or other use cases.
Maybe in this case I would keep the zazu-file-finder as it is and start acreatingseparate plugin. (maybe it could even be a root plugin without keyword, since the performance should be much much better when using an index that doing the search at runtime.

**Comment by blainesch** [comment]
For mac this is finished with the recent merge. If you want to make linux specific adapters using `locate` or `tracker` now is your chance :D
